### ISSUE TITLE
Improving Behavior When Using `read=True` ?

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/python-diskcache#11]
A couple things I've noticed in programming:

1. If I store bytes in the cache, it may choose to store the result in the database (if it's small enough). When I read those bytes back, I may request `read=True` and depending on the size of the value, I may get back a bytes object or a file handle. It seems preferable to always receive a file-like object. This is not possible for integer and floating point types but I think that's ok.
2. If I try to retrieve a value with read=True then often I would prefer to raise KeyError than return the `default`. So instead of using this pattern:

```python
try:
    with cache.get('key', read=True) as reader:
        filename = reader.name
except AttributeError: # `None` does not implement the context manager protocol.
    filename = None
```

I would prefer this pattern:

```python
try:
    with cache.get('key', read=True) as reader:
        filename = reader.name
except KeyError: # Clearly the key was not found in the cache.
    filename = None
```

But this changes the semantics of `get` when `read=True`. Should `read=True` always return a file-like object? If it used StringIO or BytesIO to do so, then the code above would break on small values because there is no filename (unless it was explicitly stored using `read=True`).

I'm starting to regret the `read=True` extension to `get` and `set` methods. Maybe the names `read` and `write` would have been better. Something like:

    cache.write('key', file_like_object)

And:

    cache.read('key') # Return file handle

I'm interested in feedback from others. If you use this functionality, please contribute your opinion.

**Comment by grantjenks** [comment]
Another thought: could separating out `read` and `write` have the added benefit of supporting unicode and bytes files?

**Comment by grantjenks** [comment]
I decided to add the `read` method but not the `write`.  A quick survey showed that the different semantics of the `read` method are quite useful.

Committed at 204762d

**Comment by darkk** [comment]
> I'm interested in feedback from others. If you use this functionality, please contribute your opinion.

My case is the following. I have ~100k blobs of the same type in the cache and the entries have very different sizes due to their nature being binary diffs between some blobs (see below). 85% of the entries are smaller than 32 KiB but the corner-case is an entry being as large as ~30 MiB, so I decided to use `read=True` feature to process the blobs in streaming way. I've found out that `read=True` actually forces small objects to be stored as files and does not respect [nice](https://www.sqlite.org/intern-v-extern-blob.html) `disk_min_file_size`:

```
$ find /srv/proj/diskcache/?? -type f -ls | awk '{print $7}' | stats
min     204
25.0%   215
50.0%   566
75.0%   17520
90.0%   43320
95.0%   55581
max     24473760
```

Then I've seen this ticket and I've seen that you use `reader.name` in some code. So my questions are the following:

Would you consider patch that respects `disk_min_file_size` while using `read=True` pre-reading `min_size` bytes from the stream and deciding if the object should be stored internally or as an external file?

Should the patch add `name` and `mode` attributes to `BytesIO` in this case to preserve some kind of compatibility? These two attributes are the only two that are present in `gzip.GzipFile`, `open`, `tempfile.TemporaryFile` while being absent from `BytesIO`.

**Comment by darkk** [comment]
Ah, thanks! I missed DjangoCache section. Now `read=True` forcing file-based store makes more sense to me. I'm still unsure if mixing `read=True` and `read=False` for the same key is possible and provides expected result, but that's not a big deal anyway.

The problem I am solving is ability to handle all my cached blobs in the same consistent way. I lean towards streaming handling as some of the blobs are quite big (~120 MiB decompressed).

However, most of the cached blobs are really small (75% under 20 KiB, 25% under 0.2 KiB). So I was surprised to see `disk_min_file_size` optimization being not respected for small files stored with `read=True`, so I decided to understand if it's a bug or a feature :-)

TBH, I don't think that it matters _much_ for me if small files are stored as filesystem objects or sqlite BLOBs. I agree that overriding the Disk object looks like the right way to implement that under the intended `read=True` use-case.

Thanks for explanation!
