### ISSUE TITLE
Tests Leave Cruft in /tmp

### ISSUE THREAD

**Issue by mgorny** [grantjenks/python-diskcache#143]
After running the test suite for *one* interpreter:

```
# ls /tmp/diskcache-
diskcache-006p6vgn/ diskcache-4tlb0tf9/ diskcache-9ot__zpv/ diskcache-cva1iy8m/ diskcache-h8a_m55k/ diskcache-ovyevvtx/ diskcache-tg91uwq6/
diskcache-28o2y76_/ diskcache-4xz4w3_x/ diskcache-9ycu4025/ diskcache-dcqgr9gb/ diskcache-hfc129vq/ diskcache-p57yjyod/ diskcache-th_urbyj/
diskcache-2c5dyvde/ diskcache-59r4apy4/ diskcache-a9kmcqid/ diskcache-dobeua9a/ diskcache-iu0iqj_o/ diskcache-pnmjm_a2/ diskcache-wkhqkru7/
diskcache-2pczjyyj/ diskcache-6b415frn/ diskcache-ablje5oy/ diskcache-_eab6j9g/ diskcache-izr25xom/ diskcache-_qefhata/ diskcache-wwiliq6v/
diskcache-2t1n4k28/ diskcache-6dnwohv7/ diskcache-ae5zs5nd/ diskcache-emzsgh3a/ diskcache-k5vmk1li/ diskcache-_qulm49q/ diskcache-xgxaxymy/
diskcache-2wfeylyy/ diskcache-6nnzwsz9/ diskcache-akx_l3a9/ diskcache-er_gr_r3/ diskcache-lr_ye9pu/ diskcache-quzccyzs/ 
diskcache-47qwdv7o/ diskcache-7ra0y_hf/ diskcache-aqz_r6fk/ diskcache-erx6y_yr/ diskcache-ma3_6ls9/ diskcache-re54hd9w/ 
diskcache-4bbou_rx/ diskcache-92ldwcdz/ diskcache-bripfybv/ diskcache-fi7ugzdf/ diskcache-n63ppv4r/ diskcache-rg9jrw3v/ 
diskcache-4j70o8q2/ diskcache-94mnp6hr/ diskcache-bttvtwsz/ diskcache-gk8ddeme/ diskcache-nsiwssft/ diskcache-rwh7hitw/ 
diskcache-4rj44zrv/ diskcache-99ngh0u6/ diskcache-c3lvb3te/ diskcache-h5mvm4y_/ diskcache-oum5djj4/ diskcache-szfse5j_/ 
```

The tests obviously don't clean up after themselves. Also, it is probably a bad idea to default to creating caches in `/tmp`.

**Comment by grantjenks** [comment]
I thought most tests did cleanup after themselves. So I wonder which leave these around.

But it’s otherwise true that I haven’t been careful about cleaning things up in /tmp. I’m not sure it matters so much. It’s never caused an issue for me before.

There have been a few times where accessing the directory after the test has been helpful for failing tests.

I think an eventual reboot will remove everything in there anyway.

**Comment by matkoniecz** [comment]
> Also, it is probably a bad idea to default to creating caches in /tmp.

Why? Main benefit is that any cruft will be cleaned by OS, typically on reboot.

**Comment by grantjenks** [comment]
I think it's all the doctests that are leaving cruft. The caches are created, used in a small snippet, and then forgotten about.

The use of /tmp is due to Python's tempfile module. It's choosing /tmp, not me.

But this seems like a fine use case of /tmp which the system will later clean anyway. I wouldn't want to delete everything at /tmp/diskcache... since those might be caches not created by pytest. I also don't really want to change the doctests.

There may be an elegant solution that applies patches before running the doctests but I don't feel that motivated to change the behavior.
