### ISSUE TITLE
v5 Changelog?

### ISSUE THREAD

**Issue by impredicative** [grantjenks/python-diskcache#153]
Is there a changelog? What's new and breaking in v5?

**Comment by grantjenks** [comment]
v5.0.1

* Remove Python 2 mapping methods keys/values/items/iter*/view*

v5.0.0

* Drop Python 2 support
* Add paragraph to caveats about cache volume for Issue #140
* Add locked method to Lock
* Add flake8 to linters and fix issues
* Remove Python 2 shims
* Update 2019 date references to 2020
* Drop PyPy testing for Django 2 support
* Use unittest.mock in tests
* Update DjangoCache tests for Django 2.2
* Drop Python 2.7 and 3.4 testing and add 3.8
* Bump Django to 2.2.*
* peekleft: fix docstr typo (#132)

**Comment by impredicative** [comment]
Thanks. Can the ongoing release changelog also be provided in a changelog doc, starting with for v5? It could be stored in a file in the repo or in [release notes](https://github.com/grantjenks/python-diskcache/releases).

**Comment by grantjenks** [comment]
Maybe. Change logs are a chore for me and the project has no donors. I'd rather folks use the git history which is tagged with version numbers.

If I had a GitHub donor page, would it be worth it to you to support the project?

**Comment by impredicative** [comment]
Changelogs are very important. It is better to release early and often. Changelogs are smaller and easier when the project is released more frequently rather than after ten months.

I don't use this project for anything commercial, so it doesn't make sense for me to donate. The git logs are generally too noisy.

**Comment by impredicative** [comment]
I am getting the impression that I need to move away from this project to something else that doesn't pester me for money when I open a reasonable technical issue.

**Comment by thinkwelltwd** [comment]
@impredicative, you asked a reasonable question, and got a reasonable answer - that one you disagree with but reasonable all the same.  @grantjenks asked a reasonable question of you in return, and your reasonable answer would've been "I don't use this project for anything commercial, so it doesn't currently make sense for me to donate." 

The surrounding commentary about "release early and often" on project with 75 releases in 4.5 years appears unreasonable to me, and it seems proper to me to come to @grantjenks  defense in pointing that out.

> I am getting the impression that I need to move away from this project to an alternative that doesn't pester me for money when I open what I consider to be a reasonable technical issue.

Instead of noisily threatening to leave, how about quietly leaving, or quietly using the project? Better yet, how about a word of thanks to @grantjenks for his work that has benefited you in some degree, even if temporarily?

**Comment by impredicative** [comment]
> Instead of noisily threatening to leave, how about quietly leaving, or quietly using the project? 

How about no? People need to know that not maintaining a changelog, and begging for money are both unprofessional activities. If someone wants to donate, they will. v5.0.2 is released, again without any changelog. No one else does this. There is nothing special about this package anyway. I can write to disk all on my own!

I will close this issue since it obviously won't ever get addressed, and I don't need it anymore anyway.

**Comment by jab** [comment]
You’re the one who’s not behaving professionally. Be polite or be on your way. Open source maintainers don’t owe you anything.

**Comment by impredicative** [comment]
@jab You're not contributing usefully to any part of this discussion. Please stick to downvoting posts you disagree with; it is something you do well.
