### ISSUE TITLE
clear() is too slow

### ISSUE THREAD

**Issue by jinserk** [grantjenks/python-diskcache#159]
I tried `clear()` to blow out the all entities in the cache, but it's too slow. All cached folder size is about 3GB, took almost 30 mins.
Doesn't it simpler to remove all the directory and its sub trees?

**Comment by grantjenks** [comment]
If you know that nothing else is accessing the cache then call close() and use shutil.rmtree() to delete the whole directory. The next time the cache is created everything will be recreated again from a blank slate.

That first “if” is the big caveat. DiskCache assumes multiple threads/processes may otherwise be accessing the cache and so can’t use rmtree() to delete everything.

Shutil’s rmtree() is already in the standard library so I don’t think there’s anything more for diskcache to provide.

Pull request welcome if there’s a place in the docs that would’ve gotten your attention.
