### ISSUE TITLE
Memoize

### ISSUE THREAD

**Issue by marcovc** [grantjenks/python-diskcache#165]
Hi,

Quick question, when I do something such as:

```python3
disk_cache = Cache()

@disk_cache.memoize()
def my_func(args):
    print("here")
    return 0
```

Shouldn't "here" be printed only once for different invocations of my_func (on distinct processes) the same tuple of "args"?

**Comment by grantjenks** [comment]
Correct. If you put that code in a file called test.py and add a line that calls my_func(1) then it will print ‘here’ the first time the script is executed and subsequent executions will not print ‘here’.

Note that two executions in parallel may each print ‘here’ because memoize() does no locking. Use the barrier() to prevent concurrent executions as described in http://www.grantjenks.com/docs/diskcache/api.html#diskcache.barrier

You may also be interested in http://www.grantjenks.com/docs/diskcache/case-study-landing-page-caching.html

**Comment by marcovc** [comment]
Thanks. That's odd, for some reason I'm not observing this. Is there any restriction on "args" or the return value types? For example, I'm trying it with args and return type as a list of dicts.

**Comment by grantjenks** [comment]
You need to give the cache a directory path. When not given, a different temporary directory Is given each time.

**Comment by marcovc** [comment]
Oh I see, thanks! I haven't noticed being mentioned in the doc, in case it isn't, it might be a good addition.

Thanks!
