### ISSUE TITLE
Please add type information to the library (mypy)

### ISSUE THREAD

**Issue by ssbarnea** [grantjenks/python-diskcache#202]
As this is a library, it would prove very useful to start adding type information to it, so we can rely on it.

```
# mypy
error: Skipping analyzing 'diskcache': found module but no type hints or library stubs
```

I personally prefer inline type instead of stubs but that would require bumping minimal python to required to 3.6 in order to be practical to implement (should not be an issue considering it already reached EOL).

**Comment by grantjenks** [comment]
How would you type the “key” and “value” parameters in the API? I think they would have to be Any which would pretty well defeat the type checker. There may be a flexible solution using generics but that also likely makes some assumptions.

Until PEP 585 becomes the minimum version (Python 3.9), I’d prefer for typing to remain in stub files. The typing imports and annotation are otherwise a bit verbose and distracting.

I’m not eager to add types myself but I wouldn’t oppose someone creating type stubs in a typeshed like diskcache-typing. It may be a nice way to get started.

**Comment by grantjenks** [comment]
Related question: how important is typing in your workflow? Is it a feature that you’d pay for?

**Comment by grantjenks** [comment]
I'm fine with someone contributing type stubs to a separate project (e.g. typing-diskcache) but I'm not planning to add types myself anytime soon (nor do I want to support them in this package if someone were to add them).

**Comment by johnraz** [comment]
@grantjenks  considering the increasing adoption of typing in Python, would you be open to re-open this (pun intended 😝 ) ? 

Thanks 🙂

**Comment by phi-friday** [comment]
I created [`diskcache-stubs`](https://github.com/phi-friday/diskcache-stubs).
It's still incomplete, but it works.

**Comment by CNSeniorious000** [comment]
Hi @phi-friday, aftering reviewing `diskcache-stubs`, I found it didn't support generic typing like this:

![dict](https://github.com/user-attachments/assets/fc8de5b1-294d-42c6-92eb-6da0ad6c2f35)

So I did some static typing and committed them in a separated package [`diskcache2`](https://github.com/CNSeniorious000/diskcache2):

Now this works:

![cache](https://github.com/user-attachments/assets/49660585-7d7e-4701-a5b2-c8a18cf724cb)

## Type Narrowing

I worked really hard into flattening the overloads for functions like `Cache.get()` and `Cache.pull()`. Look at these type narrowing results!!

![everything](https://github.com/user-attachments/assets/18b06a9e-01f2-49bc-8d62-ab5035e7cd0d)
