### ISSUE TITLE
MultiProcessing Pool and Cache Insertion

### ISSUE THREAD

**Issue by galewis2** [grantjenks/python-diskcache#217]
Hi, I'm having a problem where my original single process script happily adds elements to the cache, and can then do a `in` to finds the data. However in the multiprocess version it never adds or finds the entries.

Is there a recipe for this that I can follow? I'm working on an MVP to see if I can duplicate.

**Comment by grantjenks** [comment]
Did you give the cache a name/consistent path across all processes? The directory arg must be the same across all processes.

There are some samples otherwise:
1. http://www.grantjenks.com/docs/diskcache/case-study-web-crawler.html
2. https://github.com/grantjenks/python-diskcache/blob/master/tests/benchmark_incr.py
3. https://stackoverflow.com/questions/54886601/globally-modifiable-object-shared-across-multiple-processes-and-modules

It’s typically best to put the cache in the global vars and have each function access it from a separate process just as you would with a shared dictionary.

**Comment by galewis2** [comment]
Ha, I figured it out. I was using numpy array_split, which unbeknownst to me, was converting my strings to numpy strings. My keys being inserted weren't actually strings, so when I re-read the cache and using an `in` check, it was failing as I was looking for a string in a set of numpy.string types
