### ISSUE TITLE
Native async implementation

### ISSUE THREAD

**Issue by Archmonger** [grantjenks/python-diskcache#282]
`python-diskcache` currently relies on the built-in `sqlite` library in order to function. It would be relatively simple to duplicate the current API into an async version. This will result in much higher theoretical performance in high-utilization scenarios.

In theory, the current API could be perfectly replicated as async. For example, with `__getitem__`...

```python
class AsyncCache:
    async def __getitem__(self, __name: str):
        ...

async def test():
    cache = AsyncCache()  # non-functional example
    await cache["abc"]
```

I would recommend using [`aiosqlite`](https://github.com/omnilib/aiosqlite) for this. It likely will need to be an optional dependency.

```bash
pip install diskcache[async]
```

I would recommend validating whether or not `aiosqlite` is installed during the `__init__` of `AsyncDiskCache`. Throwing an error like this seems reasonable: `AsyncCache requires the aiosqlite dependency`.

Adding support for async within `DjangoCache` would require creating `a*` methods, such as `adelete`, `aset`, etc.

**Comment by grantjenks** [comment]
A few thoughts:

1. aiosqlite doesn’t implement a real async layer atop SQLite. Instead, it just uses threads: https://github.com/omnilib/aiosqlite/blob/main/aiosqlite/core.py#L76 The same pattern can be done with DiskCache and threads already. Just use the run_in_executor api provided by the built-in asyncio. I would expect lower utilization due to the additional threading layer overhead.

2. I don’t want to duplicate all the methods in DiskCache just to prefix the letter “a” to the methods and sprinkle the “async” keyword everywhere. I understand it’s maybe a simple source transformation but it seems burdensome from a maintenance perspective. I wish there was some way to make the same method “optionally” async.

3. Because SQLite runs in-process, even if there were a native async-friendly driver layer, what would it await? There’s no network call as there is with separate server databases like Postgres or MySQL. There’s a disk call deep inside the SQLite code but I don’t think the SQLite api exposes an async api for interacting at that low level. I don’t think Python supports async for disk reads/writes in the standard library either.

4. If it’s just the async Django cache methods that you’d like to use then the run_in_executor trick should work fine there. DiskCache needs to be updated for the Django 4.2 release too.

**Comment by GregRos** [comment]
I would really like to emphasize how important this is. Async I/O can drastically improve performance in many situations.

> aiosqlite doesn’t implement a real async layer atop SQLite. Instead, it just uses threads: https://github.com/omnilib/aiosqlite/blob/main/aiosqlite/core.py#L76 The same pattern can be done with DiskCache and threads already. Just use the run_in_executor api provided by the built-in asyncio. I would expect lower utilization due to the additional threading layer overhead.

Threads are what allows async stuff to happen at all, since it's the concurrency mechanism the OS provides. `asyncio` is an abstraction built atop this system which is nicer to use. 

So yes, if you look how async abstractions are implemented, you will find threads.

The overhead of managing threads is insignificant compared to waiting for I/O, especially since we might be doing it on an actual disk drive.

From the perspective of a user, having to wrap every call to a library with threading logic is the kind of thing that would make me look for a different library.

> Because SQLite runs in-process, even if there were a native async-friendly driver layer, what would it await? There’s no network call as there is with separate server databases like Postgres or MySQL. There’s a disk call deep inside the SQLite code but I don’t think the SQLite api exposes an async api for interacting at that low level. I don’t think Python supports async for disk reads/writes in the standard library either.

It would await another thread blocked by I/O. 

Python definitely supports doing I/O in parallel with executing code, and that's the only thing required here. 

Threads support executing arbitrary code in parallel within the same process, and they are implemented by the OS. The only thing stopping them from executing Python code in parallel in the same process is the GIL.

But if a thread is blocked by IO it doesn't have the GIL, so another thread can execute Python code. Thus we achieve parallelism. The CPU can run code while the storage controller goes rummaging for data. 

> I don’t want to duplicate all the methods in DiskCache just to prefix the letter “a” to the methods and sprinkle the “async” keyword everywhere. I understand it’s maybe a simple source transformation but it seems burdensome from a maintenance perspective. I wish there was some way to make the same method “optionally” async.

This idea of a method being "optionally" async doesn't make sense because async methods work differently and return different things. What you're suggesting is a mechanism for code generation...

Which I'm pretty sure you can do. Just attach attributes as methods to the appropriate classes during runtime. This would require generating type stubs separately. 

I don't know if it's a good idea, but it's certainly possible.

Regardless, if you don't solve this problem as part of DiskCache, you're just handing it back to the users to solve. Just like it's unpleasant to maintain all these methods with slightly different names, it's extremely unpleasant to write and maintain tons of wrappers for threading logic just to use a caching library.
