### ISSUE TITLE
copy cache folder of diskcache

### ISSUE THREAD

**Issue by arita37** [grantjenks/python-diskcache#42]
For some applications, I would like to generate cache offline (ie during week end, for week day application).
and copy the cache folder to another server/PC where the cache can be used.

Is there any limitation or is it platform dependant ?
(ex Windows ---> Linux) .

What are the limit of size for diskcarch ?
   Nb of Key, Size of each individual file (caching 1Go pandas df is ok ?)

**Comment by grantjenks** [comment]
I expect that will work fine. Regarding your questions:

1. It should work cross-platform. You can generate the cache on one machine and copy it to another.
2. There are no size limits beyond those inherited from your OS.
3. You can store as many keys as you like.
4. Keys and values can be as large as you like. It will support a 1GB Pandas dataframe just fine.

Be sure to check the settings: http://www.grantjenks.com/docs/diskcache/tutorial.html#settings when you initialize your cache. The default cache size is 1GB which you will want to increase so that large Pandas DataFrames are not evicted.

Example:
```
In [1]: import diskcache as dc

In [2]: cache = dc.FanoutCache('foo')

In [3]: for value in range(10):
   ...:     cache[value] = value
   ...:     

In [4]: cache['test'] = 'long' * 1000000

In [5]: len(cache)
Out[5]: 11

In [6]: cache.close()

In [7]: !mv foo bar

In [8]: cache = dc.FanoutCache('bar')

In [9]: len(cache)
Out[9]: 11

In [10]: for value in range(10):
   ....:     assert cache[value] == value
   ....:     

In [11]: assert cache['test'] == 'long' * 1000000

In [12]: cache.close()
```
