### ISSUE TITLE
How do I check that adding a bool False twice fails?``

### ISSUE THREAD

**Issue by piccolbo** [grantjenks/python-diskcache#50]
```
In [119]: cache.add(1,True)
Out[119]: True

In [120]: cache.add(1,True)
Out[120]: False

In [121]: cache.add(1,False)
Out[121]: False

In [122]: cache.add(1,False)
Out[122]: False
```

This API choice reminds me of C. Why not return -1 for the sake of the good old times? An exception would have been a much better choice.

**Comment by grantjenks** [comment]
You're mapping a key to a value. The key is 1 in all your cases. It returns True when you successfully add the key/value pair. False when it does not. The first call succeeds. The rest fails because the key is already there. Here's the docs: http://www.grantjenks.com/docs/diskcache/api.html#diskcache.Cache.add

**Comment by piccolbo** [comment]
I understand what's happening. That was not what the ticket was about. No worries, I will use something else.

**Comment by grantjenks** [comment]
Sorry if I misunderstood. Could you explain your use case?
