### ISSUE TITLE
How to correctly iterate caches?

### ISSUE THREAD

**Issue by Bert-Proesmans** [grantjenks/python-diskcache#63]
Hi, i'm building a small tool with Diskcache to calculate/store/compare image hashes. My current implementation uses a FanoutCache to memoize different hashes under different parameters and the intention is to use the hashes for distance calculation.
The result would be sets of image-paths with (closely) similar hashes (image deduplication).

I'm now wondering what the correct approach would be to get results back from the cache to run my similarity algorithm. As far as i understand the docs i could retrieve an index from the current fanout cache and iterate all values, but directly working with the SQLlite disk might be more interesting because i would be able to express my algorithms in SQL directly.

Do you have any thoughts or possible preferred approach you could enlighten me with?

Thank you in advance!

**Comment by grantjenks** [comment]
Happy New Year! Sorry for the delayed reply. Those Holidays tho :)

You have an important problem and one I've thought about too. I'm not sure of your exact implementation but am I right in guessing you do some combination of scaling down the image size and colors? Maybe using [ImageHash](https://pypi.python.org/pypi/ImageHash) or related?

The trick here is that hashed images have many dimensions. For example, if we take an image, switch to grayscale and scale to 16x16 pixels then we're left 256 bytes each describing one b/w pixel. We can then store those 256-byte hashes in a collection like a sorted list (or in the case of DiskCache, an indexed column). Now if we have another 256-byte hash, "h", and we want to find those hashes that it is most similar too, how would we do so? We could ask if "h" is exactly in our collection pretty easily but what if one or more pixels varies by one or more degrees? It's usually not enough to rely on sorted order because that disproportionately weights the high-order bytes.

What I did in the past was to start with the hash, "h", and calculate variants of the hash where each byte differed by one degree. In doing so, my 256-byte hash because "h" + 512 variants (each byte +/- 1). I would then lookup each variant.

But what if 2 bytes vary? Well then I wouldn't have found it. Hopefully your image hash is pretty good!

The generic problem can be solved using a K-D Tree. There's just such a data type in [SciPy](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.html). SQLite also has such a feature known as an [R-Tree](https://sqlite.org/rtree.html) but DiskCache does not use either of these.

DiskCache only provides two methods for iteration: diskcache.core.Cache.iterkeys() and iter(diskcache.core.Cache). The former iterates in key sort-order according to SQLite's [ORDER BY](https://sqlite.org/lang_select.html#orderby) clause and the latter in cache insertion-order. I would guess ordering by insertion-order is slightly faster as it uses the id of each row.

If you find DiskCache useful, consider making a [donation](https://gumroad.com/l/diskcache). Every little bit helps!

**Comment by Bert-Proesmans** [comment]
Hi, a happy new year for you as well.

First of all thank you for your response and the provided links are interesting on first look.
In the meantime i discovered that i didn't interpret the docs correctly, so i changed strategy.
As of now i'm using two passes over all data and only store the hashes for 0-distance matching into the second pass. The prototype i worked out is very crude in that regard, but i think i could fine-tune it further (if testing deems necessary) following your guidance.
